# Generated by Django 5.1.1 on 2024-11-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('issue', 'Issue'), ('bug_fix', 'Bug Fix')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('issue', 'Issue'), ('bug_fix', 'Bug Fix')], max_length=255, verbose_name='Type'),
        ),
    ]
